name: 🐍 Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write  # Needed to push to output branch

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Required to make sure the workflow can access your repo and push
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate the contribution snake SVG + GIF
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: nishuR31
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif

      # Push the rendered files to the output branch
      - name: Push to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
